# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/solver_app-0.1.0.0-Linux
Summary:        C++ application for solving quadratic equations
Name:           solver-app
Version:        0.1.0.0
Release:        1
License:        MIT
Group:          Development/Tools
Vendor:         Your Name


















Prefix: /usr





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename solver_app-0.1.0.0-Linux.rpm
%define _unpackaged_files_terminate_build 0



%define _binary_payload w7T1.xzdio

%description
Solver application for quadratic equations


# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)
/usr/bin/hello_world_app
/usr/bin/solver_app
%dir /usr/include/solver
/usr/include/solver/formatter.h
/usr/include/solver/formatter_ex.h
/usr/include/solver/solver.h
/usr/lib/libformatter.a
/usr/lib/libformatter_ex.a
/usr/lib/libsolver.a
%dir /usr/share/doc/solver-app
/usr/share/doc/solver-app/LICENSE
/usr/share/doc/solver-app/README.md




%changelog
* Thu Apr 30 2026 tonemtonem <kosstylev.ds@gmail.com> 0.1.0.0
- Initial release
- Includes solver_app application
- CMake-based build system
- CI/CD with GitHub Actions



